//Register

export const preference = {
  PREFERENCE_START: "PREFERENCE_START",
  PREFERENCE_SUCCESS: "PREFERENCE_SUCCESS",
  PREFERENCE_ERROR: "PREFERENCE_ERROR",
};
//Register

//Login

export const userProfile = {
  USER_PROFILE_START: "USER_PROFILE_START",
  USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
  USER_PROFILE_ERROR: "USER_PROFILE_ERROR",
};
//Login
