//Register

export const register = {
  REGISTER_START: "REGISTER_START",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_ERROR: "REGISTER_ERROR",
};
//Register

//Login

export const userProfile = {
  USER_PROFILE_START: "USER_PROFILE_START",
  USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
  USER_PROFILE_ERROR: "USER_PROFILE_ERROR",
};
//Login
